# Generated by Django 2.1.3 on 2019-10-12 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apistep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apistep', models.CharField(max_length=100, null=True, verbose_name='测试步聚')),
                ('apiname', models.CharField(max_length=100, verbose_name='接口名称')),
                ('apiurl', models.CharField(max_length=200, verbose_name='url 地址')),
                ('apiheaders', models.CharField(help_text='请写入json格式的数据.如果为空则填写"/"', max_length=1000, verbose_name='请求头信息')),
                ('apiparamvalue', models.CharField(help_text='请写入json格式的数据.如果为空则填写"/"', max_length=800, verbose_name='请求参数和值')),
                ('apimethod', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='get', max_length=200, null=True, verbose_name='请求方法')),
                ('apistatuscode', models.CharField(max_length=3, verbose_name='状态码')),
                ('apiresult', models.CharField(help_text='多个校验时使用分号隔开.如name==admin;price=1', max_length=5000, verbose_name='预期结果')),
                ('apiresponse', models.CharField(blank=True, max_length=5000, null=True, verbose_name='响应结果')),
                ('apistatus', models.BooleanField(null=True, verbose_name='是否通过')),
                ('create_time', models.DateField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Apitest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apitestname', models.CharField(max_length=64, verbose_name='流程名称')),
                ('apitestdesc', models.CharField(max_length=64, null=True, verbose_name='描述')),
                ('apitester', models.CharField(max_length=16, verbose_name='测试负责人')),
                ('apitestresult', models.BooleanField(verbose_name='测试结果')),
                ('failreason', models.CharField(blank=True, max_length=5000, null=True, verbose_name='失败原因')),
                ('create_time', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('Items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Items')),
            ],
            options={
                'verbose_name': '场景测试',
                'verbose_name_plural': '场景测试',
            },
        ),
        migrations.CreateModel(
            name='SingeApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiname', models.CharField(max_length=100, verbose_name='接口名称')),
                ('apidesc', models.CharField(blank=True, help_text='接口描述|用途', max_length=100, null=True, verbose_name='接口描述|用途')),
                ('apiurl', models.CharField(max_length=1000, verbose_name='url 地址')),
                ('apiheaders', models.CharField(help_text='请求头信息;请写入json格式的数据.如果为空则填写"/"', max_length=1000, verbose_name='请求头信息')),
                ('apiparamvalue', models.CharField(help_text='请写入json格式的数据.如果为空则填写"/"', max_length=1000, verbose_name='请求参数和值')),
                ('apimethod', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='post', max_length=200, null=True, verbose_name='请求方法')),
                ('apistatuscode', models.CharField(max_length=3, verbose_name='状态码')),
                ('apiresult', models.CharField(help_text='预期结果;多个校验时使用分号隔开.如name=admin;price=1', max_length=5000, verbose_name='预期结果')),
                ('apiresponse', models.CharField(blank=True, max_length=5000, null=True, verbose_name='响应结果')),
                ('apistatus', models.BooleanField(verbose_name='是否通过')),
                ('create_time', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='执行时间')),
                ('ItemsApplication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ItemsApplication')),
            ],
            options={
                'verbose_name': '接口信息',
                'verbose_name_plural': '接口信息',
            },
        ),
        migrations.AddField(
            model_name='apistep',
            name='Apitest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Apitest'),
        ),
    ]
