# Generated by Django 2.1.3 on 2019-10-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20191012_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apitest',
            options={'verbose_name': '场景测试', 'verbose_name_plural': '场景测试'},
        ),
        migrations.AlterModelOptions(
            name='singeapi',
            options={'verbose_name': '接口信息', 'verbose_name_plural': '接口信息'},
        ),
    ]
