# Generated by Django 2.1.3 on 2019-10-12 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bugname', models.CharField(help_text='BUG名称', max_length=100, verbose_name='BUG名称')),
                ('bugdesc', models.CharField(help_text='复现步骤', max_length=5000, verbose_name='复现步骤')),
                ('bugimgFile', models.ImageField(blank=True, help_text='BUG截图', null=True, upload_to='image', verbose_name='BUG截图')),
                ('bugstatus', models.CharField(choices=[('激活', '激活'), ('已解决', '已解决'), ('已关闭', '已关闭'), ('挂起', '挂起')], default='激活', max_length=200, null=True, verbose_name='解决状态')),
                ('buglevel', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='2', max_length=200, null=True, verbose_name='严重级别')),
                ('bugcreater', models.CharField(max_length=10, verbose_name='BUG创建者')),
                ('bugrepair', models.CharField(max_length=10, verbose_name='指派给')),
                ('createtime', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('ItemsApplication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.ItemsApplication')),
            ],
            options={
                'verbose_name': 'BUG名称',
                'verbose_name_plural': 'BUG名称',
            },
        ),
    ]
