# Generated by Django 2.1.3 on 2019-10-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='参数名字', max_length=20, verbose_name='参数名字')),
                ('value', models.CharField(help_text='设置参数的值', max_length=500, verbose_name='参数值')),
                ('createTime', models.DateField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '参数信息',
                'verbose_name_plural': '参数信息',
            },
        ),
    ]
