# Generated by Django 2.1.3 on 2019-11-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0002_auto_20191127_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='desc',
            field=models.CharField(max_length=300, null=True, verbose_name='功能介绍'),
        ),
    ]
